// app/wines/mockWines.ts
import { components } from "@/types/types";

export type WineListType = components["schemas"]["WineListType"];

export const mockWines: WineListType[] = [
  {
    id: 1,
    name: "Sentinel Cabernet Sauvignon 2016",
    region: "Western Cape, South Africa",
    image: "/assets/images/wine/wine1.png",
    price: 45000,
    type: "RED",
    avgRating: 4.8,
    reviewCount: 12,
    recentReview: null,
    userId: 1,
  },
  {
    id: 2,
    name: "Palazzo della Torre 2017",
    region: "Western Cape, South Africa",
    image: "/assets/images/wine/wine2.png",
    price: 150000,
    type: "RED",
    avgRating: 4.6,
    reviewCount: 20,
    recentReview: null,
    userId: 1,
  },
  {
    id: 3,
    name: "Sentinel Carbernet Sauvignon 2016",
    region: "Western Cape, South Africa",
    image: "/assets/images/wine/wine3.png",
    price: 220000,
    type: "SPARKLING",
    avgRating: 4.9,
    reviewCount: 30,
    recentReview: null,
    userId: 2,
  },
  {
    id: 4,
    name: "Sassicaia 2018",
    region: "Tuscany",
    image: "/assets/images/wine/wine4.png",
    price: 180000,
    type: "RED",
    avgRating: 4.7,
    reviewCount: 18,
    recentReview: null,
    userId: 3,
  },
  {
    id: 5,
    name: "Cloudy Bay Sauvignon Blanc 2020",
    region: "Marlborough",
    image: "/assets/images/wine/wine4.png",
    price: 60000,
    type: "WHITE",
    avgRating: 4.5,
    reviewCount: 25,
    recentReview: null,
    userId: 4,
  },
  {
    id: 6,
    name: "Moët & Chandon Impérial Brut",
    region: "Champagne",
    image: "/assets/images/wine/wine4.png",
    price: 90000,
    type: "SPARKLING",
    avgRating: 4.6,
    reviewCount: 40,
    recentReview: null,
    userId: 5,
  },
];
