/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    "_36_Enums.Aroma":
      | "CHERRY"
      | "BERRY"
      | "OAK"
      | "VANILLA"
      | "PEPPER"
      | "BAKING"
      | "GRASS"
      | "APPLE"
      | "PEACH"
      | "CITRUS"
      | "TROPICAL"
      | "MINERAL"
      | "FLOWER"
      | "TOBACCO"
      | "EARTH"
      | "CHOCOLATE"
      | "SPICE"
      | "CARAMEL"
      | "LEATHER";
    Aroma: components["schemas"]["_36_Enums.Aroma"];
    ReviewUser: {
      /** Format: double */
      id: number;
      nickname: string;
      image: string | null;
    };
    WineListType: {
      /** Format: double */
      id: number;
      name: string;
      region: string;
      image: string;
      /** Format: double */
      price: number;
      type: string;
      /** Format: double */
      avgRating: number;
      /** Format: double */
      reviewCount: number;
      recentReview: {
        user: components["schemas"]["ReviewUser"];
        /** Format: date-time */
        updatedAt: string;
        /** Format: date-time */
        createdAt: string;
        content: string;
        aroma: components["schemas"]["Aroma"][];
        /** Format: double */
        rating: number;
        /** Format: double */
        id: number;
      } | null;
      /** Format: double */
      userId: number;
    };
    /** @enum {string} */
    "_36_Enums.WineType": "RED" | "WHITE" | "SPARKLING";
    WineType: components["schemas"]["_36_Enums.WineType"];
    CreateWineBody: {
      name: string;
      region: string;
      image: string;
      /** Format: double */
      price: number;
      type: components["schemas"]["WineType"];
    };
    CursorBasedPaginationResponse_WineListType_: {
      /** Format: double */
      totalCount: number;
      /** Format: double */
      nextCursor: number | null;
      list: components["schemas"]["WineListType"][];
    };
    Boolean: Record<string, never>;
    ReviewListType: {
      /** Format: double */
      id: number;
      /** Format: double */
      rating: number;
      /** Format: double */
      lightBold: number;
      /** Format: double */
      smoothTannic: number;
      /** Format: double */
      drySweet: number;
      /** Format: double */
      softAcidic: number;
      aroma: components["schemas"]["Aroma"][];
      content: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      user: components["schemas"]["ReviewUser"];
      isLiked?: components["schemas"]["Boolean"];
    };
    /** @description Construct a type with a set of properties K of type T */
    "Record_number.number_": {
      [key: string]: number;
    };
    WineDetailType: {
      /** Format: double */
      id: number;
      name: string;
      region: string;
      image: string;
      /** Format: double */
      price: number;
      type: string;
      /** Format: double */
      avgRating: number;
      /** Format: double */
      reviewCount: number;
      recentReview: {
        user: components["schemas"]["ReviewUser"];
        /** Format: date-time */
        updatedAt: string;
        /** Format: date-time */
        createdAt: string;
        content: string;
        aroma: components["schemas"]["Aroma"][];
        /** Format: double */
        rating: number;
        /** Format: double */
        id: number;
      } | null;
      /** Format: double */
      userId: number;
      reviews: components["schemas"]["ReviewListType"][];
      avgRatings: components["schemas"]["Record_number.number_"];
    };
    Wine: {
      /** Format: double */
      id: number;
      name: string;
      region: string;
      image: string;
      /** Format: double */
      price: number;
      /** Format: double */
      avgRating: number;
      type: components["schemas"]["WineType"];
    };
    UpdateWineBody: {
      name?: string;
      region?: string;
      image?: string;
      /** Format: double */
      price?: number;
      /** Format: double */
      avgRating?: number;
      type?: components["schemas"]["WineType"];
    };
    /** Format: int32 */
    Id: number;
    /** @example 닉네임 */
    Nickname: string;
    /**
     * Format: url
     * @example https://example.com/...
     */
    UrlType: string;
    User: {
      image: components["schemas"]["UrlType"] | null;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      createdAt: string;
      teamId: string;
      nickname: components["schemas"]["Nickname"];
      id: components["schemas"]["Id"];
    };
    CursorBasedPaginationResponse_ReviewListType_: {
      /** Format: double */
      totalCount: number;
      /** Format: double */
      nextCursor: number | null;
      list: components["schemas"]["ReviewListType"][];
    };
    UpdateUserBody: {
      image?: components["schemas"]["UrlType"];
      nickname?: components["schemas"]["Nickname"];
    };
    ReviewDetailType: {
      /** Format: double */
      id: number;
      /** Format: double */
      rating: number;
      /** Format: double */
      lightBold: number;
      /** Format: double */
      smoothTannic: number;
      /** Format: double */
      drySweet: number;
      /** Format: double */
      softAcidic: number;
      aroma: components["schemas"]["Aroma"][];
      content: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      user: components["schemas"]["ReviewUser"];
      isLiked?: components["schemas"]["Boolean"];
      /** Format: double */
      wineId: number;
      teamId: string;
    };
    CreateReviewBody: {
      /** Format: double */
      rating: number;
      /** Format: double */
      lightBold: number;
      /** Format: double */
      smoothTannic: number;
      /** Format: double */
      drySweet: number;
      /** Format: double */
      softAcidic: number;
      aroma: components["schemas"]["Aroma"][];
      content: string;
      /** Format: double */
      wineId: number;
    };
    UpdateReviewBody: {
      /** Format: double */
      rating?: number;
      /** Format: double */
      lightBold?: number;
      /** Format: double */
      smoothTannic?: number;
      /** Format: double */
      drySweet?: number;
      /** Format: double */
      softAcidic?: number;
      aroma?: components["schemas"]["Aroma"][];
      content?: string;
    };
    /** @enum {string} */
    "_36_Enums.OauthProvider": "GOOGLE" | "NAVER" | "KAKAO";
    OauthProvider: components["schemas"]["_36_Enums.OauthProvider"];
    /** @description 간편 로그인을 위한 인증 키 입니다.
     *
     *     * Google 의 경우에는 "클라이언트 id" 입니다.
     *     * Kakao 의 경우에는 "REST API 키" 입니다.
     *     * Naver 의 경우에는 "Client ID" 입니다.
     *
     *     실습을 위해 발급받은 키를 등록해주세요. 실제 서비스에서 사용 하는 키는 등록하시면 안됩니다. */
    AppKey: string;
    /** @description 간편 로그인을 위한 비밀 키 입니다.
     *
     *     * Google 의 경우에는 필요하지 않습니다.
     *     * Kakao 의 경우에는 필요하지 않습니다.
     *     * Naver 의 경우에는 "Client Secret" 입니다. */
    AppSecret: string;
    OauthApp: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      appSecret: components["schemas"]["AppSecret"] | null;
      appKey: components["schemas"]["AppKey"];
      provider: components["schemas"]["OauthProvider"];
      teamId: string;
      id: components["schemas"]["Id"];
    };
    UpsertOauthAppRequestBody: {
      appSecret?: components["schemas"]["AppSecret"];
      appKey: components["schemas"]["AppKey"];
      provider: components["schemas"]["OauthProvider"];
    };
    /**
     * Format: email
     * @example example@email.com
     */
    Email: string;
    SignUpResponse: {
      refreshToken: string;
      accessToken: string;
      user: components["schemas"]["User"] & {
        email: components["schemas"]["Email"];
      };
    };
    /** @example password */
    Password: string;
    SignUpRequestBody: {
      image?: components["schemas"]["UrlType"];
      passwordConfirmation: components["schemas"]["Password"];
      password: components["schemas"]["Password"];
      nickname: components["schemas"]["Nickname"];
      email: components["schemas"]["Email"];
    };
    SignInResponse: {
      refreshToken: string;
      accessToken: string;
      user: components["schemas"]["User"] & {
        email: components["schemas"]["Email"];
      };
    };
    SignInRequestBody: {
      password: components["schemas"]["Password"];
      email: components["schemas"]["Email"];
    };
    /** @description 간편 로그인 과정을 통해 발급받은 토큰입니다.<br />
     *
     *     * Google 의 경우에는 <b>Google Id 토큰</b>(JWT) 입니다.
     *     * Kakao 의 경우에는 <b>인가 코드</b> 입니다.
     *     * Naver 의 경우에는 <b>code</b> 입니다. */
    OauthToken: string;
    SignInWithOauthRequestBody: {
      /** @description Naver 의 경우에는 필수입니다.<br/>
       *     code를 얻을 때 사용하였던 state 값을 그대로 사용합니다. */
      state?: string;
      /**
       * @description Kakao 의 경우에는 필수입니다.<br/>
       *     인가 코드를 얻을 때 사용하였던 redirect_uri 값을 그대로 사용합니다.
       * @example http://localhost:3000/oauth/kakao
       */
      redirectUri?: string;
      token: components["schemas"]["OauthToken"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
